### PR TITLE
Update to new smartcitizen connector

### LINKED ISSUE #49: Smart Citizen doesn't show up
Due to the new changes on the Smart Citizen API, we get a `404` when getting the `kits` endpoint.

Traceback:
```
[2024-04-22 16:11:43] - [ERROR] API reported 404
Traceback (most recent call last):
  File "/home/xxxxxxx/mecoda_orange/smartcitizen_search.py", line 12, in <module>
    class SmartcitizenSearchWidget(OWBaseWidget):
  File "/home/xxxxxxx/mecoda-orange/mecoda_orange/smartcitizen_search.py", line 42, in SmartcitizenSearchWidget
    descriptive_blueprints = blueprints = ('', ) + tuple(sorted("{0:0=2d}".format(kit.id) + ': ' + kit.name for kit in blueprints),)
                                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

### PR DESCRIPTION
**Pull request by oscgonfer**
This should fix #49.
@pynomaly, please test the PR before merging just in case.

### CODE REVIEW

**Comment by pynomaly** [comment]
Not working for me, when running: 
`python smartcitizen_search.py `

The widget loads correctly and display the filters. When I set "City: Barcelona", I got:
```
[2024-05-02 13:47:12,854] - smartcitizen_connector - INFO - Admin Bearer not found
INFO:smartcitizen_connector:Admin Bearer not found
[2024-05-02 13:47:12,856] - smartcitizen_connector - INFO - Getting: https://api.smartcitizen.me/v0/devices/?q[tags_name_in]=barcelona
INFO:smartcitizen_connector:Getting: https://api.smartcitizen.me/v0/devices/?q[tags_name_in]=barcelona
```
Message: "Nothing found". 

Maybe I'm using incorrectly the filters. Could you give me an example of a search to test?

**Comment by oscgonfer** [comment]
Oh, that's strange. I just tried with 'Barcelona' and it got me: https://api.smartcitizen.me/v0/devices/?q[tags_name_in]=Barcelona

Can you try with capital B? Or in the `user` field, use `oscgonfer`

**Comment by pynomaly** [comment]
Error with Barcelona search:
```
[2024-05-02 14:13:55,215] - smartcitizen_connector - INFO - Admin Bearer not found
INFO:smartcitizen_connector:Admin Bearer not found
[2024-05-02 14:13:55,216] - smartcitizen_connector - INFO - Getting: https://api.smartcitizen.me/v0/devices/?q[tags_name_in]=Barcelona
INFO:smartcitizen_connector:Getting: https://api.smartcitizen.me/v0/devices/?q[tags_name_in]=Barcelona
Traceback (most recent call last):
  File "/home/anomalia/projects/mecoda-orange/mecoda_orange/smartcitizen_search.py", line 223, in commit
    devices['owner_id'] = devices.apply(dict_unpack, column='owner', key='id', axis=1)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/anomalia/projects/mecoda-orange/.venv/lib/python3.11/site-packages/pandas/core/frame.py", line 10361, in apply
    return op.apply().__finalize__(self, method="apply")
           ^^^^^^^^^^
  File "/home/anomalia/projects/mecoda-orange/.venv/lib/python3.11/site-packages/pandas/core/apply.py", line 916, in apply
    return self.apply_standard()
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/anomalia/projects/mecoda-orange/.venv/lib/python3.11/site-packages/pandas/core/apply.py", line 1063, in apply_standard
    results, res_index = self.apply_series_generator()
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/anomalia/projects/mecoda-orange/.venv/lib/python3.11/site-packages/pandas/core/apply.py", line 1081, in apply_series_generator
    results[i] = self.func(v, *self.args, **self.kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/anomalia/projects/mecoda-orange/.venv/lib/python3.11/site-packages/smartcitizen_connector/tools/tools.py", line 286, in dict_unpack
    return row[column][key]
           ~~~~~~~~~~~^^^^^
TypeError: 'float' object is not subscriptable
```
If I add "user: oscgonfer", I get: 3 devices gathered.

**Comment by oscgonfer** [comment]
Let me relaunch this PR. It's incorrectly rebase due to an inconsistency on my end.

**Pull request closed without merging**
